// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJk31w2P-nnPqnfKDYxfOJoDzThcDZa0',
    appId: '1:612181539550:web:c92eb790ff96da0be0a04f',
    messagingSenderId: '612181539550',
    projectId: 'smartcanteen-49b04',
    authDomain: 'smartcanteen-49b04.firebaseapp.com',
    storageBucket: 'smartcanteen-49b04.firebasestorage.app',
    measurementId: 'G-YC6H3VF2EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCukaVYw9Lmj65lZTDZgCwDpktL9K-2l0k',
    appId: '1:98490570517:android:82770052dfe3df96debb1c',
    messagingSenderId: '98490570517',
    projectId: 'coffe-shop-6cd83',
    storageBucket: 'coffe-shop-6cd83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiByiGTOQvI1a-UaHpgB3RMjgQ77R-pNM',
    appId: '1:612181539550:ios:5cbdccf9f369d3ace0a04f',
    messagingSenderId: '612181539550',
    projectId: 'smartcanteen-49b04',
    storageBucket: 'smartcanteen-49b04.firebasestorage.app',
    iosBundleId: 'com.example.smartcanteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiByiGTOQvI1a-UaHpgB3RMjgQ77R-pNM',
    appId: '1:612181539550:ios:5cbdccf9f369d3ace0a04f',
    messagingSenderId: '612181539550',
    projectId: 'smartcanteen-49b04',
    storageBucket: 'smartcanteen-49b04.firebasestorage.app',
    iosBundleId: 'com.example.smartcanteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJJk31w2P-nnPqnfKDYxfOJoDzThcDZa0',
    appId: '1:612181539550:web:7985f994bb6aef72e0a04f',
    messagingSenderId: '612181539550',
    projectId: 'smartcanteen-49b04',
    authDomain: 'smartcanteen-49b04.firebaseapp.com',
    storageBucket: 'smartcanteen-49b04.firebasestorage.app',
    measurementId: 'G-SHNRNCY6WN',
  );
}
